### PR TITLE
Add Unwound Jukebox

### PR DESCRIPTION
**Pull request by pokmon987**

### CODE REVIEW

**Comment by Yuqera** [comment]
Looked over the PR looked really great, but I do have a few questions:
 - Why has gradle.build, gitignore, and bat been removed?
 - Is it possible to use a normal jukebox if it's functionality is only to rewind the watch and while it's playing do the checks for lower time anomalies+show particles? Or do you think we should keep to an unique jukebox?
 - 
 
 Great things btw:
  - WatchWrapper
  - Love the particles
  - Great improvements on the BlockHistoryHandler

**Comment by pokmon987** [comment]
Yeah, I'm not really experienced with using github and its commands, but I had to edit some of those files to get the repo to work on my end, and to prevent those changes from being pushed to the origin, I just removed them. You can use the git cherry-pick command to accept all of the changes except for the gradle.build, .gitignore, and gradlew.bat.

I'll experiment a little with the tile entity stuff, and maybe try some other things to get rewinding to tick, but the way the unwound jukebox works is that you click on a normal jukebox with the deactivated watch, and it turns color and emits particles, and then if its broken before it finishes, it drops the watch and the normal jukebox, or when it finishes it drops the watch and turns into a normal jukebox. It's not a block that should stay.

**Comment by Yuqera** [comment]
Awesome, I'll just cherry pick the rest of the files then since it's all looking pretty good. I'll also create an issue so that we remember to remove the Unwound Jukebox in the future.

Also just 1 question before I approve this PR and merge it, are the Time Crystals meant to be a place holder for now?

**Comment by pokmon987** [comment]
Yes, the time crystals are place holder just for the sake of testing the jukebox

**Comment by Yuqera** [comment]
Alright then I know enough, I'll start merging this PR now. We'll remove any place holders at the end. In the development stage it's still acceptable.

**Review by Yuqera — APPROVED** [review]

**Pull request merged**
